"""add core domain models

Revision ID: e694bcc659db
Revises: 
Create Date: 2026-03-15 15:16:45.111533

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e694bcc659db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('admission_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cycle', sa.String(length=12), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('is_published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('year', 'cycle', name='uq_admission_processes_year_cycle')
    )
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_area_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['academic_area_id'], ['academic_areas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_area_id', 'name', name='uq_faculties_academic_area_name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_faculties_academic_area_id', 'faculties', ['academic_area_id'], unique=False)
    op.create_table('majors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'name', name='uq_majors_faculty_name'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_majors_faculty_id', 'majors', ['faculty_id'], unique=False)
    op.create_table('admission_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admission_process_id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('candidate_code', sa.String(length=64), nullable=False),
    sa.Column('candidate_lastnames', sa.String(length=160), nullable=False),
    sa.Column('candidate_names', sa.String(length=160), nullable=False),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('merit_rank', sa.Integer(), nullable=True),
    sa.Column('observation_raw', sa.Text(), nullable=True),
    sa.Column('is_admitted', sa.Boolean(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['admission_process_id'], ['admission_processes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('admission_process_id', 'major_id', 'candidate_code', name='uq_admission_results_process_major_candidate')
    )
    op.create_index('ix_admission_results_admission_process_id', 'admission_results', ['admission_process_id'], unique=False)
    op.create_index('ix_admission_results_candidate_code', 'admission_results', ['candidate_code'], unique=False)
    op.create_index('ix_admission_results_is_admitted', 'admission_results', ['is_admitted'], unique=False)
    op.create_index('ix_admission_results_major_id', 'admission_results', ['major_id'], unique=False)
    op.create_index('ix_admission_results_process_major', 'admission_results', ['admission_process_id', 'major_id'], unique=False)
    op.create_index('ix_admission_results_score', 'admission_results', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admission_results_score', table_name='admission_results')
    op.drop_index('ix_admission_results_process_major', table_name='admission_results')
    op.drop_index('ix_admission_results_major_id', table_name='admission_results')
    op.drop_index('ix_admission_results_is_admitted', table_name='admission_results')
    op.drop_index('ix_admission_results_candidate_code', table_name='admission_results')
    op.drop_index('ix_admission_results_admission_process_id', table_name='admission_results')
    op.drop_table('admission_results')
    op.drop_index('ix_majors_faculty_id', table_name='majors')
    op.drop_table('majors')
    op.drop_index('ix_faculties_academic_area_id', table_name='faculties')
    op.drop_table('faculties')
    op.drop_table('admission_processes')
    op.drop_table('academic_areas')
    # ### end Alembic commands ###
