# Generated by Django 6.1 on 2026-08-27 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='academics_a_is_acti_503b86_idx')],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculties', to='academics.academicarea')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='majors', to='academics.faculty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['academic_area', 'is_active'], name='academics_f_academi_60a04c_idx'),
        ),
        migrations.AddIndex(
            model_name='faculty',
            index=models.Index(fields=['is_active', 'name'], name='academics_f_is_acti_a250f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('academic_area', 'code'), name='unique_faculty_code_per_area'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['faculty', 'is_active'], name='academics_m_faculty_b9f5aa_idx'),
        ),
        migrations.AddIndex(
            model_name='major',
            index=models.Index(fields=['is_active', 'name'], name='academics_m_is_acti_8e27cf_idx'),
        ),
    ]
