# Generated by Django 6.1 on 2026-08-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionModality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active', 'name'], name='admission_p_is_acti_91a94b_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('sequence', models.CharField(max_length=32)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'sequence'],
                'indexes': [models.Index(fields=['-year', 'sequence'], name='admission_p_year_11e58c_idx'), models.Index(fields=['is_published', '-year'], name='admission_p_is_publ_0dcfe4_idx')],
                'constraints': [models.UniqueConstraint(fields=('year', 'sequence'), name='unique_admission_process')],
            },
        ),
    ]
